---
kind: pipeline
name: Codequality

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.4
  commands:
  - php -v
  - composer update
  - composer require phpmd/phpmd phpstan/phpstan
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: phpcs
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards
  - vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/

- name: phpmd
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpmd src text cleancode
  - vendor/bin/phpmd src text codesize
  - vendor/bin/phpmd src text controversial
  - vendor/bin/phpmd src text design
  - vendor/bin/phpmd src text unusedcode
  failure: ignore

- name: phpstan
  image: joomlaprojects/docker-images:php7.4
  commands:
  - vendor/bin/phpstan analyse src
  failure: ignore

- name: phploc
  image: joomlaprojects/docker-images:php7.4
  commands:
  - phploc src
  failure: ignore

- name: phpcpd
  image: joomlaprojects/docker-images:php7.4
  commands:
  - phpcpd src
  failure: ignore

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 5.3 lowest

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php5.3
  commands:
  - php -v
  - composer update --prefer-stable --prefer-lowest
  - composer update phpunit/phpunit-mock-objects
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php5.3
  commands:
  - ""
  - locale-gen fr_FR.utf8
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 5.3

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php5.3
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php5.3
  commands:
  - ""
  - locale-gen fr_FR.utf8
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 5.4

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php5.4
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php5.4
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 5.5

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php5.5
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php5.5
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 5.6

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php5.6
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php5.6
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.0

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.0
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.0
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.1

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.1
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.1
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.2

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.2
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.2
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.3

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.3
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.3
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 7.4

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php7.4
  commands:
  - php -v
  - composer --version
  - composer update --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php7.4
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: pipeline
name: PHP 8.0

platform:
  os: linux
  arch: amd64

steps:
- name: composer
  image: joomlaprojects/docker-images:php8.0
  commands:
  - php -v
  - composer --version
  - composer update --ignore-platform-reqs --prefer-stable
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache

- name: PHPUnit
  image: joomlaprojects/docker-images:php8.0
  commands:
  - apt install -y locales && sed -i 's/^# *\(fr_FR.UTF-8\)/\1/' /etc/locale.gen && locale-gen
  - ""
  - update-locale
  - locale -a
  - vendor/bin/phpunit
  failure: ignore

volumes:
- name: composer-cache
  host:
    path: /tmp/composer-cache

---
kind: signature
hmac: dd34d9101dfb1b93e84d8ac1b7c80523cae9da31280590cd6132321e05762d9b

...
